config/routes.rb
Rails.application.routes.draw do

  get 'home/index' => 'home#index'

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get 'log-out' => 'sessions#destroy'
  
  root 'home#index'

  resources :transactions
  resources :users
  resources :candidates

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @candidates = Candidate.all
      @candidate = Candidate.find_by(id: @i)
      @user = current_user
      	# dem is an array of democratic primary results returned from Iowa markets
      	# @dem = Iowa::Client.new.dem['results']['collection1']
        @dem = Candidate.d_get_data
      	# i stands in for the position in the array
      	@i = 0
      	# dem_array_length is the length of the dem array
      	@dem_array_length = @dem.length

        # need to define these for the data array used in the graphs
        @clin = @dem[0]['Average'].to_f
        @sand = @dem[1]['Average'].to_f
        @dem_rof = @dem[2]['Average'].to_f

        # need to define these for the backup data array used in the graphs
        @clinL = @dem[0]['Last'].to_f
        @sandL = @dem[1]['Last'].to_f
        @dem_rofL = @dem[2]['Last'].to_f
        
      	
      	# rep is an array of republican primary results returned from Iowa markets
      	@rep = Candidate.r_get_data
      	# x stands in for the position in the array
      	@x = 0
      	# dem_array_lsength is the length of the rep array minus 1
      	@rep_array_length = @rep.length
      	@z = 0

        @car = @rep[0]['Average'].to_f
        @cruz = @rep[1]['Average'].to_f
        @rub = @rep[2]['Average'].to_f
        @trump = @rep[3]['Average'].to_f
        @rep_rof = @rep[4]['Average'].to_f

        @carL = @rep[0]['Last'].to_f
        @cruzL = @rep[1]['Last'].to_f
        @rubL = @rep[2]['Last'].to_f
        @trumpL = @rep[3]['Last'].to_f
        @rep_rofL = @rep[4]['Last'].to_f
      else
        redirect_to log_in_path
      end

  	# dem_api_url = '9wmpnk9k?apikey=tj1hdT1m9XSPUeh1LyEyBn7Q7mC6qIDg'
  	# rep_api_url = 'bj8hlwos?apikey=tj1hdT1m9XSPUeh1LyEyBn7Q7mC6qIDg'
  	# @dem_old_data = Iowa::Client.new.old_data['results']['collection1']
  	# @rep_old_data = Iowa::Client.new.old_data(y, rep_api_url)['results']['collection1']

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dem_graph.html.erb
<div class="dem_graph"></div>
	<script src="https://d3js.org/d3.v3.js"></script>
	<script type="text/javascript">
		// creates the svg viewport selection, where the graph is going to live and be buit
		var width = 650
		var height = 401

		var svgContainer = d3.select(".dem_graph").append("svg")
			.attr("width", width)
			.attr("height", height);

		// var can_name = ['Clinton', 'Sanders', 'Dem_ROF', 'Carson', 'Cruz', 'Rubio', 'Trump', 'Rep_ROF']

		var data = [<%= @clin %>, <%= @sand %>, <%= @dem_rof %>]
		var lastdata	 = [<%= @clinL %>, <%= @sandL %>, <%= @dem_rofL %>]
		
		// creates the scale that the graph is going to use for the x axis
		var xaxisScale = d3.scale.ordinal()
			.domain(['Clinton', 'Sanders', 'Dem_ROF'])
			.rangeRoundBands([0, 600], .1);

		// creates the scale that the graph is going to use for the y axis
		var yaxisScale = d3.scale.linear()
			.domain([0.00, 1.00])
			.range([250, 0])
		// actually creates the axis
		var xAxis = d3.svg.axis()
			.scale(xaxisScale);

		var yAxis = d3.svg.axis()
			.scale(yaxisScale)
			.ticks(5)
			.orient("left");

		// creates an SVG group element (g) for the axis elements to be housed within and calls the xAxis function - this is what puts it on the page
		var xAxisGroup = svgContainer.append("g")
			.attr("class", "axis")
			.attr("transform", "translate(80, 330)")
			.call(xAxis);

		var yAxisGroup = svgContainer.append("g")
			.attr("class", "axis")
			.attr("transform", "translate(85, 85)")
			.call(yAxis);

		// 
		svgContainer.append("text")
			.attr("class", "title")
			.attr("x", (width / 2))
			.attr("y", 70)
			.attr('transform', 'translate(40, 0)')
			.style("text-anchor", "middle")
			.text("Democratic Party")

		var bar = svgContainer.selectAll('g')
		<% if @clin || @sand || @dem_rof == '---' %>
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.enter()
			.append('g')
			.attr("transform", function(d) { return "translate(" + xAxisGroup(d) + ",0)"; });

		bar.append("rect")
		<% if @clin || @sand || @dem_rof == '---' %>
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.enter()
			.append("rect")
			.attr("x", function(d, i) {
				return i * (570 / data.length); // this makes a bar with a couple pixels of padding
			})
			.attr("y", function(d) {
				return 270 - (d * 250);
			})
			.attr("width", 80)
			.attr("height", function(d) {
				return d * 250;
			})
			.attr('transform', 'translate(145, 59)');

		bar.append("text")
		<% if @clin || @sand || @dem_rof == '---' %>
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.enter()
			.append("text")
	    	.attr("x", function(d, i) { return i * (570 / data.length) })
	    	.attr("y", function(d) { return 270 - (d * 250); })
	    	.attr("dy", ".75em")
	    	.text(function(d) { return d; })
	    	.attr('transform', 'translate(165, 40)')
	    	.attr('class', 'num');


	</script>
	

app/views/home/_rep_graph.html.erb
<div class="rep_graph"></div>
	<script src="https://d3js.org/d3.v3.js"></script>
	<script type="text/javascript">
		// creates the svg viewport selection, where the graph is going to live and be buit
		var width = 665
		var height = 396

		var svgContainer = d3.select(".rep_graph").append("svg")
			.attr("width", width)
			.attr("height", height);

		// var can_name = ['Clinton', 'Sanders', 'Dem_ROF', 'Carson', 'Cruz', 'Rubio', 'Trump', 'Rep_ROF']

		var data = [<%= @car %>, <%= @cruz %>, <%= @rub %>, <%= @trump %>, <%= @rep_rof %>]
		var lastdata = [<%= @carL %>, <%= @cruzL %>, <%= @rubL %>, <%= @trumpL %>, <%= @rep_rofL %>]
		
		// creates the scale that the graph is going to use for the x axis
		var xaxisScale = d3.scale.ordinal()
			.domain(['Carson', 'Cruz', 'Rubio', 'Trump', 'Rep_ROF'])
			.rangeRoundBands([0, 600], .1);

		// creates the scale that the graph is going to use for the y axis
		var yaxisScale = d3.scale.linear()
			.domain([0.00, 1.00])
			.range([250, 0])
		// actually creates the axis
		var xAxis = d3.svg.axis()
			.scale(xaxisScale);

		var yAxis = d3.svg.axis()
			.scale(yaxisScale)
			.ticks(5)
			.orient("left");

		// creates an SVG group element (g) for the axis elements to be housed within and calls the xAxis function - this is what puts it on the page
		var xAxisGroup = svgContainer.append("g")
			.attr("class", "axis")
			.attr("transform", "translate(80, 330)")
			.call(xAxis);

		var yAxisGroup = svgContainer.append("g")
			.attr("class", "axis")
			.attr("transform", "translate(85, 85)")
			.call(yAxis);

		svgContainer.append("text")
			.attr("class", "title")
			.attr("x", (width / 2))
			.attr("y", 70)
			.attr('transform', 'translate(40, 0)')
			.style("text-anchor", "middle")
			.text("Republican Party")

		var bar = svgContainer.selectAll("g")
		<% if @car || @cruz || @rub || @trump || @rep_rof == '---' %>
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.enter()
			.append('g')
			.attr("transform", function(d) { return "translate(" + xAxisGroup(d) + ",0)"; });


		bar.append("rect")
		<% if @car || @cruz || @rub || @trump || @rep_rof == '---' %>
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.attr('class', 'num')
			.enter()
			.append("rect")
			.attr("x", function(d, i) { return i * (590 / data.length); })
			// this makes a bar with a couple pixels of padding
			.attr("y", function(d) { return 270 - (d * 250); })
			.attr("width", 50)
			.attr("height", function(d) { return d * 250; })
			.attr('transform', 'translate(118, 59)');

		bar.append("text")
		<% if @car || @cruz || @rub || @trump || @rep_rof == '---' %>
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.enter()
			.append("text")
	    	.attr("x", function(d, i) { return i * (590 / data.length) })
	    	.attr("y", function(d) { return 270 - (d * 250); })
	    	.attr("dy", ".75em")
	    	.text(function(d) { return d; })
	    	.attr('transform', 'translate(120, 40)')
	    	.attr('class', 'num');

	</script>
	

app/views/home/index.html.erb
<div id = 'page'>
	<div id="above_the_fold">
		<div class="dsplash_image">
			<%= image_tag("dems.png") %>
		</div>
		<div class="duser_graph">
			<%= render partial: 'dem_graph', local: {user: @user} %>
		</div>
		<div class="ruser_graph">
			<%= render partial: 'rep_graph', local: {user: @user} %>
		</div>
		<div class="rsplash_image">
			<%= image_tag("reps.jpg") %>
		</div>
	</div>
	<div class="graph"></div>
	<script src="https://d3js.org/d3.v3.js"></script>
	<script type="text/javascript">
		// creates the svg viewport selection, where the graph is going to live and be buit
		var width = 645
		var height = 375

		var svgContainer = d3.select(".graph").append("svg")
			.attr("width", width)
			.attr("height", height);

		// creates the title for the graph
		svgContainer.append("text")
			.attr("class", "title")
			.attr("x", (width / 2))
			.attr("y", 70)
			.attr('transform', 'translate(-30, 0)')
			.style("text-anchor", "middle")
			.text("Overall Race")

		// creates an array of variables that refers back to the current averge prices of the candidates for use in the graph
		var data = [<%= @clin %>, <%= @sand %>, <%= @dem_rof %>, <%= @car %>, <%= @cruz %>, <%= @rub %>, <%= @trump %>, <%= @rep_rof %>]

		// creates an array of variables that refers back to the last reported prices for the candidates, to be used if the current data isn't displaying
		var lastdata = [<%= @clinL %>, <%= @sandL %>, <%= @dem_rofL %>, <%= @carL %>, <%= @cruzL %>, <%= @rubL %>, <%= @trumpL %>, <%= @rep_rofL %>]
		
		// creates the scale that the graph is going to use for the x axis
		var xaxisScale = d3.scale.ordinal()
			.domain(['Clinton', 'Sanders', 'Dem_ROF', 'Carson', 'Cruz', 'Rubio', 'Trump', 'Rep_ROF'])
			.rangeRoundBands([0, 600], .1);

		// creates the scale that the graph is going to use for the y axis
		var yaxisScale = d3.scale.linear()
			.domain([0.00, 1.00])
			.range([250, 0])
		// actually creates the axis
		var xAxis = d3.svg.axis()
			.scale(xaxisScale);

		var yAxis = d3.svg.axis()
			.scale(yaxisScale)
			.ticks(5)
			.orient("left");

		// creates an SVG group element (g) for the axis elements to be housed within and calls the xAxis function - this is what puts it on the page
		var xAxisGroup = svgContainer.append("g")
			.attr("class", "axis")
			.attr("transform", "translate(30, 320)")
			.call(xAxis);

		var yAxisGroup = svgContainer.append("g")
			.attr("class", "axis")
			.attr("transform", "translate(35, 75)")
			.call(yAxis);


		// creates groups for each of the bars and labels to go inside

		var bar = svgContainer.selectAll('g')
		<% if @clin || @sand || @dem_rof || @car || @cruz || @rub || @trump || @rep_rof == '---' %>
		// one weak link in the array results in the last value being displayed for all candidates
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.enter()
			.append('g')
			.attr("transform", function(d) { return "translate(" + xAxisGroup(d) + ",0)"; });


		bar.append("rect")
		<% if @clin || @sand || @dem_rof || @car || @cruz || @rub || @trump || @rep_rof == '---' %>
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.enter()
			.append("rect")
			.attr("x", function(d, i) { return i * (600 / data.length); })
			// this makes a bar with a couple pixels of padding
			.attr("y", function(d) { return 270 - (d * 250); })
			.attr("width", 50)
			.attr("height", function(d) { return d * 250; })
			.attr('transform', 'translate(45, 49)');

		bar.append("text")
		<% if @clin || @sand || @dem_rof || @car || @cruz || @rub || @trump || @rep_rof == '---' %>
			.data(lastdata)
		<% else %>
			.data(data)
		<% end %>
			.enter()
			.append('text')
			.attr("x", function(d, i) { return i * (600 / data.length); })
			.attr("y", function(d) { return 270 - (d * 250); })
			.attr("dy", ".75em")
	    	.text(function(d) { return d; })
			.attr('transform', 'translate(65, 30)')
			.attr('class', 'num');

	</script>
	
	
	<div class='party dparty'>
		<h1 class="larger_text clear">Democrats</h1>
		<% while @i < @dem_array_length do %>
			<div class="dcandidate">
				<% @c = @dem[@i] %>
				<% if @c['Symbol'] == 'CLIN_NOM' %>
					<h1><%= link_to 'Hillary Clinton', candidate_path(@i + 1), class: 'cand_name' %></h1>
					<%= image_tag("clinton.jpg", class: "candidate_img") %>
				<% elsif @c['Symbol'] == 'SAND_NOM' %>
					<h1><%= link_to 'Bernie Sanders', candidate_path(@i + 1), class: 'cand_name' %></h1>
					<%= image_tag("sanders.jpg", class: "candidate_img") %>
				<% else %>
					<h1><%= link_to 'Democratic Rest of Field', candidate_path(@i + 1), class: 'cand_name' %></h1>
					<%= image_tag("democraticlogo.png", class: "candidate_img") %>
				<% end %>
				<h2><%= @c['Symbol'] %></h2>
				<p>average: <%= @c['Average'] %></p>
				<p>last: <%= @c['Last'] %></p>
			</div>
			<% @i += 1 %>
		<% end %>
	</div>
	<br>
	<div class='party rparty'>
		<h1 class="larger_text">Republicans</h1>
		<% while @x < @rep_array_length do %>
			<div class = 'candidate'>
				<% @c = @rep[@x] %>
				<% if @c['Symbol'] == 'CARS_NOM' %>
					<h1><%= link_to 'Ben Carson', candidate_path(@i + 1), class: 'cand_name' %></h1>
					<%= image_tag("carson.jpg", class: "candidate_img") %>
				<% elsif @c['Symbol'] == 'CRUZ_NOM' %>
					<h1><%= link_to 'Ted Cruz', candidate_path(@i + 1), class: 'cand_name' %></h1>
					<%= image_tag("cruz.jpg", class: "candidate_img") %>
				<% elsif @c['Symbol'] == 'RUBI_NOM' %>
					<h1><%= link_to 'Marco Rubio', candidate_path(@i + 1), class: 'cand_name' %></h1>
					<%= image_tag("rubio.jpg", class: "candidate_img") %>
				<% elsif @c['Symbol'] == 'TRUM_NOM' %>
					<h1><%= link_to 'Donald Trump', candidate_path(@i + 1), class: 'cand_name' %></h1>
					<%= image_tag("trump.jpg", class: "candidate_img") %>
				<% else %>
					<h1><%= link_to 'Republican Rest of Field', candidate_path(@i + 1), class: 'cand_name' %></h1>
					<%= image_tag("republicanlogo.jpg", class: "candidate_img") %>
				<% end %>
				<h2><%= @c['Symbol'] %></h2>
				<p>average: <%= @c['Average'] %></p>
				<p>last: <%= @c['Last'] %></p>
			</div>
			<% @x += 1 %>
			<% @i += 1 %>
		<% end %>
	</div>



	
</div>