config/routes.rb
Rails.application.routes.draw do

  get 'home/index' => 'home#index'

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get 'log-out' => 'sessions#destroy'
  
  root 'home#index'

  resources :transactions
  resources :users
  resources :candidates

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buy-In Election</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://d3js.org/d3.v3.js"></script>

</head>
<body>
	<% if flash[:notice] %>
		<div class="notice flash" ><%= flash[:notice] %></div>
	<% end %>

	<% if flash[:alert] %>
		<div class="alert flash"><%= flash[:alert] %></div>
	<% end %>
	
	<% if !current_user %>
	<header>
		<h1 class="title">
			<%= link_to 'Buy-In Election', root_path %>
		</h1>
		<nav>
			<ul>
				<li>
					<%= link_to "LOG IN", log_in_path, :class => "link" %>
				</li>
				<li>
					<%= link_to "SIGN UP", new_user_path, :class => "link" %>
				</li>
			</ul>
		</nav>
	</header>
	<% else %>
	<header>
		<h1 class="title">
			<%= link_to 'Buy-In Election', root_path %>
		</h1>
		<nav>
			<ul>
				<li>
					<%= link_to "HOME", root_path, :class => "link"%>
				</li>
				<li>
					<%= link_to "ABOUT", "#", :class => "modal-link link"%>
				</li>
				<li>
					<%= link_to "ACCOUNT", user_path(@user), :class => "link" %>
				</li>
				<li>
					<%= link_to "LOG OUT", log_out_path, :class => "link" %>
				</li>
			</ul>
		</nav>
	</header>
	<% end %>
		
	<div class="outer-modal">
		<div class="inner-modal">
				<h1>Welcome to Buy-In Election!</h1>
				<p>
					Buy-In Election is an simulated election-futures market that uses the University of Iowa Electronic Markets (IEM) to provide up-to-date pricing data on individual futures contracts. For the layman, within the scope of this app, the terms "future", "contract", and "stock" are effectively interchangeable.  Individual stocks oscillate in value from $0.001 to $0.999. At the end of the nomination (or, later, the general election) cycle, stockholders will receive $1 for every winning contract.
				</p>
				<ul>Further Details on Futures Market:
					<li> <a href="http://tippie.uiowa.edu/iem/markets/pr_dconv16.html">IEM Democratic Convention Market</a></li>
					<li> <a href="http://tippie.uiowa.edu/iem/markets/pr_rconv16.html">IEM Republican Convention Market</a></li>
				</ul>
				<br><br>
				Created by <a href="https://github.com/andrew-schultz">Andy</a> and <a href="https://github.com/thisisniall">Niall</a> for <a href="http://nycda.com">NYCDA</a>.
		</div>
	</div>

<%= yield %>

	<footer>
	</footer>
<script src="https://d3js.org/d3.v3.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>